name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'resident_tracking/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ./resident_tracking
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Deploy to Streamlit Cloud
        uses: streamlit/streamlit-app-action@v0.1.0
        with:
          app-path: resident_tracking/app.py
          streamlit-app-url: https://resident-doctors-tracking.streamlit.app
